artifacts:
  artifacts_dir: artifacts
  trained_model_dir: model
  base_model_dir: base_model
  base_model_name: VGG16_base_model.h5
  updated_base_model_name: updated_VGG16_base_model.h5
  checkpoint_dir: checkpoints
  base_log_dir: base_log_dir
  tensorboard_root_log_dir: tensorboard_root_log
  callbakc_dir: callbacks

source_download_path:
  cat:  data_folder_download/cat
  dog: data_folder_download/dog

source_folder:
  cat: data_folder/cat
  dog: data_folder/dog

